apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-slave
spec:
  serviceAccountName: jenkins-admin
  securityContext:                  #容器安全设置
    runAsUser: 0                    #以ROOT用户运行容器
    privileged: true                #赋予特权执行容器
  containers:
  - name: jnlp                      #Jenkins Slave镜像
    image: registry.cn-shanghai.aliyuncs.com/mydlq/jenkins-jnlp-slave:3.27-1
    #设置工作目录
    workingDir: /home/jenkins
    tty: true
  - name: docker                    #Docker镜像
    image: registry.cn-shanghai.aliyuncs.com/mydlq/docker:18.06.2-dind
    command: ['cat']
    tty: true
    volumeMounts:
    - name: docker
      mountPath: /usr/bin/docker
    - name: docker-sock
      mountPath: /var/run/docker.sock
    - name: docker-config
      mountPath: /etc/docker
  - name: maven                     #Maven镜像
    image: registry.cn-shanghai.aliyuncs.com/mydlq/maven:3.6.0-jdk8-alpine
    command:
    - cat
    tty: true
    volumeMounts:
    - name: maven-m2
      mountPath: /root/.m2
  - name: kubectl              #Kubectl & Helm镜像
    image: registry.cn-shanghai.aliyuncs.com/mydlq/helm-kubectl:2.13.1
    command:
    - cat
    tty: true

  - name: nodejs
    image: andonescu/jdk-8-node-docker-gcp:latest
    command:
    - cat
    tty: true
    volumeMounts:
    - name: nodejs
      mountPath: /root/nodejs


  volumes:
  - name: docker                    #将宿主机 Docker 文件夹挂进容器，方便存储&拉取本地镜像
    hostPath: 
      path: /usr/bin/docker
  - name: docker-sock               #将宿主机 Docker.sock 挂进容器
    hostPath: 
      path: /var/run/docker.sock
  - name: docker-config             #将宿主机 Docker 配置挂在进入容器
    hostPath: 
      path: /etc/docker
  - name: maven-m2
    persistentVolumeClaim:
       claimName: maven-slaves-pvc
       readOnly: false
  - name: nodejs
    persistentVolumeClaim:
       claimName: nodejs-slaves-pvc
       readOnly: false
